#!/usr/bin/env python3
"""Compress the payload ELF with raw DEFLATE (RFC 1951) and emit a C source
file that replaces the old `xxd -i` output.

Usage: deflate.py <input-elf> <output.c>

The generated file provides (all consumed by src/bootstrap-bin.c):
  - DB_REBUILDER_ELF_RAW_SIZE  : size of the original (decompressed) ELF
  - db_rebuilder_elf[]         : the raw-deflate compressed ELF image
  - db_rebuilder_elf_len       : length of the compressed image

Raw deflate (no zlib/gzip wrapper) is used because the bootstrap inflates
the image with puff(), which expects a bare RFC 1951 stream.
"""

import sys
import zlib


def main() -> int:
    if len(sys.argv) != 3:
        sys.stderr.write("usage: deflate.py <input-elf> <output.c>\n")
        return 1

    src_path, dst_path = sys.argv[1], sys.argv[2]

    with open(src_path, "rb") as f:
        raw = f.read()

    comp = zlib.compressobj(9, zlib.DEFLATED, -15)  # raw deflate, max level
    blob = comp.compress(raw) + comp.flush()

    lines = []
    lines.append("/* Auto-generated by tools/deflate.py. Do not edit. */")
    lines.append("")
    lines.append("/* Size of the original uncompressed payload ELF. */")
    lines.append("#define DB_REBUILDER_ELF_RAW_SIZE %dUL" % len(raw))
    lines.append("")
    lines.append("/* Raw-DEFLATE (RFC 1951) compressed payload ELF. */")
    lines.append("const unsigned char db_rebuilder_elf[] = {")
    for off in range(0, len(blob), 12):
        chunk = blob[off:off + 12]
        lines.append("  " + ", ".join("0x%02x" % b for b in chunk) + ",")
    lines.append("};")
    lines.append("")
    lines.append("const unsigned int db_rebuilder_elf_len = %d;" % len(blob))
    lines.append("")

    with open(dst_path, "w", newline="\n") as f:
        f.write("\n".join(lines))

    print("deflate: %s: %d -> %d bytes (%.1f%%)"
          % (src_path, len(raw), len(blob), 100.0 * len(blob) / max(1, len(raw))))
    return 0


if __name__ == "__main__":
    sys.exit(main())
